### ISSUE TITLE
License + Docker Hub

### ISSUE THREAD

**Issue by rafaelstz** [dsantiago/big-data-environment#1]
Primeiramente parabéns, gostei da organização dos containers embora conheça superficialmente as tecnologias.
Tenho duas sugestões que poderia ser implementado em suas próximas milestones, a primeira é colocar no Docker Hub e linka-las. A segunda é colocar a licença em que você disponibiliza esse repositório e o seu nome com link para refletir em forks customizados :smile:.

**Comment by dsantiago** [comment]
Fala Sertão, e ae... então cara está funcional porque algumas pessoas pediram mas tem muito a melhorar ainda, não sei se você manja das ferramentas de big data mas está usando ferramentas dentro do stack cloudera e eu não queria isto.... Então ainda é um "work-in-progress" e por hora vai ficar escondidinho... No futuro até penso em fazer melhorias visto que nunca vi nada parecido na internet e olha que pesquisei demais..
